version: '3.8'

services:
  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"  # LocalStack Gateway
      - "4510-4559:4510-4559"  # External services
    environment:
      - SERVICES=lambda,sqs,dynamodb
      - DEFAULT_REGION=us-east-1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./lambda-localstack-project:/lambda-localstack-project
    networks:
      - localstack-network

networks:
  localstack-network:
    driver: bridge